predict.tree<-function(final.tree,y.new,X.new){
  tree<-as.matrix(final.tree);
  n<-nrow(X.new);	
  class<-rep(100,n);
  l<-nrow(tree);
  for(i in 1:n){
    flag<-0;t=1;
    while(t<=l & flag==0){
      if(tree[t,1]==1){
        if((!is.na(tree[t,2]))){if(X.new[i,1]<=tree[t,2]){class[i]=0;flag=1;}};
        if((!is.na(tree[t,5]))){if(X.new[i,1]>=tree[t,5]){class[i]=1;flag=1;}};
      }
      if(tree[t,1]==2){
        if((!is.na(tree[t,2]))){if(X.new[i,2]>=tree[t,2]){class[i]=0;flag=1;}};
        if((!is.na(tree[t,5]))){if(X.new[i,2]<=tree[t,5]){class[i]=1;flag=1;}};
      }
      if(tree[t,1]==3){
        if((!is.na(tree[t,2]))){if(X.new[i,3]>=tree[t,2]){class[i]=0;flag=1;}};
        if((!is.na(tree[t,5]))){if(X.new[i,3]<=tree[t,5]){class[i]=1;flag=1;}};
      }
      if(tree[t,1]==4){
        if((!is.na(tree[t,2]))){if(X.new[i,4]<=tree[t,2]){class[i]=0;flag=1;}};
        if((!is.na(tree[t,5]))){if(X.new[i,4]>=tree[t,5]){class[i]=1;flag=1;}};
      }
      t<-t+1;
    }   
  }
  result<-cbind(y.new,class);
  return(result);
}
